"""HTTP API for the Q&A service and the eval dashboard.

- GET  /health          indexed versions
- POST /retrieve        version choice + retrieved chunks (Voyage only, no Claude cost)
- POST /ask             Server-Sent Events: `version`, `hits`, then `answer` (or `error`)
- GET  /examples        answers generated by the latest dev eval run, for the demo
- GET  /eval/results    run summaries for the dashboard

Live answers call Claude on the operator's key, so they are off unless LIVE_ANSWERS=true;
every call still goes through the dollar ledger (rag.billing). The demo shows /examples.

Usage:
    uv run uvicorn api.main:app --reload
"""

import json
import time
from collections.abc import Iterator
from dataclasses import asdict
from functools import lru_cache
from pathlib import Path
from typing import Annotated

import psycopg
from fastapi import Depends, FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from rag.embedders import EMBEDDERS
from rag.generate import Answer, generate
from rag.query import VersionChoice, choose_version, indexed_versions
from rag.retrieve import DEFAULT, Hit, RetrievalConfig, retrieve
from rag.settings import get_settings

ROOT = Path(__file__).resolve().parent.parent
RESULTS_DIR = DEFAULT_RESULTS_DIR = ROOT / "eval" / "results"
EXAMPLES_RUN = "dev-default"

app = FastAPI(title="k8s-docs-rag")


class Question(BaseModel):
    question: str = Field(min_length=3, max_length=1000)
    version: str | None = Field(default=None, pattern=r"^1\.\d{1,2}$")
    k: int = Field(default=DEFAULT.k, ge=1, le=20)


# ---------------------------------------------------------------------------- dependencies


def get_conn() -> Iterator[psycopg.Connection]:
    with psycopg.connect(get_settings().database_url) as conn:
        yield conn


def get_embedder():
    return EMBEDDERS["voyage-4"]


@lru_cache
def get_claude():
    """The ledger-guarded client, or None when live answers are disabled."""
    settings = get_settings()
    if not settings.live_answers:
        return None
    from rag.billing import make_client

    return make_client()


Conn = Annotated[psycopg.Connection, Depends(get_conn)]
Embedder = Annotated[object, Depends(get_embedder)]
Claude = Annotated[object | None, Depends(get_claude)]


# ---------------------------------------------------------------------------- serialization


def hit_json(h: Hit) -> dict:
    return {**asdict(h), "score": round(h.score, 4)}


def answer_json(a: Answer) -> dict:
    return {
        "text": a.text,
        "found": a.found,
        "stop_reason": a.stop_reason,
        "sources": [
            {
                "number": s.number,
                "url": s.hit.url,
                "title": " > ".join(p for p in s.hit.heading_path if p) or s.hit.title,
                "chunk_id": s.hit.chunk_id,
                "cited_texts": s.cited_texts,
            }
            for s in a.sources
        ],
        "usd": round(a.usd, 6),
    }


def sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


# ---------------------------------------------------------------------------- endpoints


@app.get("/health")
def health() -> dict:
    return {"status": "ok", "versions": list(indexed_versions())}


def search(conn, embedder, q: Question) -> tuple[VersionChoice, list[Hit], dict]:
    choice = choose_version(q.question, q.version)
    t0 = time.monotonic()
    [vector], _ = embedder.embed([q.question], "query")
    t1 = time.monotonic()
    config = RetrievalConfig(**{**DEFAULT.__dict__, "k": q.k})
    hits = retrieve(conn, q.question, vector, choice.version, config, model=embedder.name)
    t2 = time.monotonic()
    return choice, hits, {"embed": round(t1 - t0, 3), "retrieve": round(t2 - t1, 3)}


@app.post("/retrieve")
def retrieve_endpoint(q: Question, conn: Conn, embedder: Embedder):
    choice, hits, latency = search(conn, embedder, q)
    return {"version": asdict(choice), "hits": [hit_json(h) for h in hits], "latency": latency}


@app.post("/ask")
def ask_endpoint(q: Question, conn: Conn, embedder: Embedder, claude: Claude):
    if claude is None:
        raise HTTPException(403, "Live answers are disabled on this server; see /examples.")

    def events() -> Iterator[str]:
        try:
            choice, hits, latency = search(conn, embedder, q)
            yield sse("version", asdict(choice))
            yield sse("hits", {"hits": [hit_json(h) for h in hits], "latency": latency})
            t0 = time.monotonic()
            answer = generate(claude, q.question, choice.version, hits, choice.note)
            latency["generate"] = round(time.monotonic() - t0, 3)
            yield sse("answer", {**answer_json(answer), "latency": latency})
        except Exception as e:  # the stream has started; report instead of dropping it
            yield sse("error", {"type": type(e).__name__, "message": str(e)})

    return StreamingResponse(events(), media_type="text/event-stream")


def read_jsonl(path: Path) -> list[dict]:
    return [json.loads(line) for line in path.read_text().splitlines()] if path.exists() else []


@app.get("/examples")
def examples() -> dict:
    rows = read_jsonl(RESULTS_DIR / "generation" / f"{EXAMPLES_RUN}.jsonl")
    keep = ("id", "category", "version", "question", "answer", "found", "sources")
    return {"run": EXAMPLES_RUN, "examples": [{k: r[k] for k in keep} for r in rows]}


CI_SAMPLES = 2000  # fewer than eval.report's 10,000: enough for display, fast per request


def intervals(kind: str, stem: str) -> dict:
    """metric -> [mean, lo, hi], from the per-item result files (eval.report)."""
    from eval import report

    if kind == "retrieval":
        scores = report.retrieval_scores(stem)
    else:
        scores, _ = report.generation_scores(stem)
    return {
        m: [round(x, 4) for x in report.bootstrap_ci(list(v.values()), samples=CI_SAMPLES)]
        for m, v in scores.items()
        if v
    }


@app.get("/eval/results")
def eval_results() -> dict:
    out = {}
    for kind in ("retrieval", "generation"):
        runs = []
        for p in sorted((RESULTS_DIR / kind).glob("*.summary.json")):
            if ".judge-" in p.name:
                continue
            summary = json.loads(p.read_text())
            stem = p.name.removesuffix(".summary.json")
            judges = sorted((RESULTS_DIR / kind).glob(f"{stem}.judge-*.summary.json"))
            if judges:
                summary["judge"] = json.loads(judges[-1].read_text())
            if RESULTS_DIR == DEFAULT_RESULTS_DIR:
                summary["ci"] = intervals(kind, stem)
            runs.append({"run": stem, **summary})
        out[kind] = runs
    return out
